version: '3.8'

volumes:
  mongodb-volumes:

networks:
  rotten-potatoes-net:
    driver: bridge

services:
  mongodb: 
    image: mongo
    ports:
      - 27017:27017
    networks:
      - rotten-potatoes-net
    volumes:
      - mongodb-volumes:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      
  rotten-potatoes: 
    image: fernandoy2203/rotten-potatoes:v1
    ports:
      - 5000:5000
    networks:
      - rotten-potatoes-net
    environment:
        MONGODB_HOST: mongodb
        MONGODB_USERNAME: mongouser
        MONGODB_PASSWORD: mongopwd
  
  